language: elixir
elixir:
  - '1.9.4'
otp_release:
  - '22.0'
env:
  - MIX_ENV=test
services:
  - postgresql
  - docker
before script:
  - psql -c 'create database banking_api_test;' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'masterkey';" -U postgres
script:
  - "mix do deps.get, test --trace && mix compile && mix coveralls.travis"  
after_success:  
  - docker login -u _ -p "$HEROKU_API_KEY" registry.heroku.com
  - docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile .
  - docker tag back $DOCKER_USER/$HEROKU_APP_NAME:$TRAVIS_BUILD_NUMBER
  - docker push registry.heroku.com/$HEROKU_APP_NAME/web
  - docker push $DOCKER_USER/$HEROKU_APP_NAME:latest  
  - heroku container:release web -a $HEROKU_APP_NAME
  - heroku run "./bin/banking_api eval 'BankingApi.Release.migrate()'" -a $HEROKU_APP_NAME