language: elixir
elixir:
  - '1.9.4'
otp_release:
  - '22.0'
env:
  - MIX_ENV=test
services:
  - postgresql
  - docker
before script:
  - psql -c 'create database banking_api_test;' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'masterkey';" -U postgres
script:
  - "mix do deps.get, test --trace && mix compile && mix coveralls.travis"  
after_success:  
  - docker login -u _ -p "$HEROKU_API_TOKEN" registry.heroku.com
  - docker build -t registry.heroku.com/azex-banking-api/web -f Dockerfile .
  - docker tag back $DOCKER_USER/azex-banking-api:$TRAVIS_BUILD_NUMBER
  - docker push registry.heroku.com/azex-banking-api/web
  - docker push $DOCKER_USER/banking-api:latest  
  - heroku container:release web -a azex-banking-api
  - heroku run "./bin/banking_api eval 'BankingApi.Release.migrate()'"