language: elixir
elixir:
  - '1.9.4'
otp_release:
  - '22.0'
env:
  - MIX_ENV=test
service:
  - postgresql
before script:
  - psql -c 'create database banking_api_test;' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'masterkey';"
script:
  - "mix do deps.get, test --trace && mix compile && mix coveralls.travis"